apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-redis-data
  namespace: staging-infra
  labels:
    app: authentik-redis
    component: idp-cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-media
  namespace: staging-infra
  labels:
    app: authentik
    component: idp-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
