apiVersion: v1
kind: Service
metadata:
  name: authentik-redis
  namespace: staging-infra
  labels:
    app: authentik-redis
    component: idp-cache
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    app: authentik-redis
